import { describe, expect, it } from "vitest";

import type { FullMetadata } from "../src/engine.js";
import { defaultExportPath, metadataToMarkdown } from "../src/markdown.js";

function fakeFull(pretty: Record<string, unknown>): FullMetadata {
  return { pretty, numeric: pretty };
}

describe("metadataToMarkdown", () => {
  const report = fakeFull({
    FileName: "photo.jpg",
    FileType: "JPEG",
    Make: "SONY",
    Model: "ILCE-7M4",
    ShutterCount: 12345,
    ObscureTag: "some | piped | value",
  });

  const md = metadataToMarkdown([report], {
    version: "9.9.9",
    date: new Date("2026-07-05T12:00:00Z"),
  });

  it("has a per-file heading and key fields table", () => {
    expect(md).toContain("## photo.jpg");
    expect(md).toContain("### Key fields");
    expect(md).toContain("| Field | Value |");
    expect(md).toContain("| Camera | SONY ILCE-7M4 |");
    expect(md).toContain("| Shutter count | 12,345 |");
  });

  it("includes the remaining tags in their own table", () => {
    expect(md).toContain("### All other tags (1)");
    expect(md).toContain("ObscureTag");
  });

  it("escapes pipes inside values", () => {
    expect(md).toContain("some \\| piped \\| value");
  });

  it("stamps tool version and date", () => {
    expect(md).toContain("Generated by exifregistry v9.9.9 on 2026-07-05 12:00 UTC.");
  });

  it("renders one section per file", () => {
    const two = metadataToMarkdown([
      fakeFull({ FileName: "a.jpg" }),
      fakeFull({ FileName: "b.jpg" }),
    ]);
    expect(two).toContain("## a.jpg");
    expect(two).toContain("## b.jpg");
  });
});

describe("defaultExportPath", () => {
  it("derives <stem>.metadata.md next to a single file", () => {
    expect(defaultExportPath(["/photos/IMG_1234.CR3"])).toBe(
      "/photos/IMG_1234.metadata.md",
    );
  });

  it("uses a generic name for batches", () => {
    expect(defaultExportPath(["a.jpg", "b.jpg"])).toBe("exif-report.md");
  });
});
