/**
 * Export metadata reports as Markdown files.
 *
 * Reuses the same curated/other split as the terminal report, so the .md
 * mirrors exactly what `show`/Inspect displays.
 */

import * as path from "node:path";

import { fullReportRows } from "./display.js";
import type { FullMetadata } from "./engine.js";

/** Escape a value for use inside a Markdown table cell. */
function esc(value: string): string {
  return value.replace(/\r?\n/g, " ").replace(/\|/g, "\\|");
}

function table(rows: [string, string][], header: [string, string]): string[] {
  return [
    `| ${header[0]} | ${header[1]} |`,
    "| --- | --- |",
    ...rows.map(([k, v]) => `| ${esc(k)} | ${esc(v)} |`),
    "",
  ];
}

export interface MarkdownOptions {
  /** exifregistry version stamped in the report footer. */
  version?: string;
  /** Generation timestamp (defaults to now). */
  date?: Date;
}

/** Render one or more metadata reports as a single Markdown document. */
export function metadataToMarkdown(
  reports: FullMetadata[],
  options: MarkdownOptions = {},
): string {
  const date = options.date ?? new Date();
  const stamp = date.toISOString().slice(0, 16).replace("T", " ") + " UTC";
  const tool = options.version ? `exifregistry v${options.version}` : "exifregistry";

  const lines: string[] = ["# Metadata report", ""];
  for (const report of reports) {
    const { main, other } = fullReportRows(report);
    const name = String(report.pretty.FileName ?? "unknown file");
    lines.push(`## ${esc(name)}`, "");
    lines.push("### Key fields", "");
    lines.push(...table(main, ["Field", "Value"]));
    if (other.length > 0) {
      lines.push(`### All other tags (${other.length})`, "");
      lines.push(...table(other, ["Tag", "Value"]));
    }
  }
  lines.push("---", "", `Generated by ${tool} on ${stamp}.`, "");
  return lines.join("\n");
}

/**
 * Default export path: next to a single inspected file
 * ("photo.jpg" -> "photo.metadata.md"), or "exif-report.md" for batches.
 */
export function defaultExportPath(inspectedFiles: string[]): string {
  if (inspectedFiles.length === 1) {
    const file = inspectedFiles[0];
    const dir = path.dirname(file);
    const stem = path.basename(file, path.extname(file));
    return path.join(dir, `${stem}.metadata.md`);
  }
  return "exif-report.md";
}
